apiVersion: apps/v1
kind: Deployment
metadata:
  name: skill
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skill
  template:
    metadata:
      labels:
        app: skill
    spec:
      containers:
      - image: okteto.dev/skill:latest
        name: skill
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "dca3cee3-53c3-4196-bb35-39cc1d552511"
        - name: Vless_Path
          value: "/heel"
        - name: Vmess_UUID
          value: "dca3cee3-53c3-4196-bb35-39cc1d552511"
        - name: Vmess_Path
          value: "/heemo"
        - name: Share_Path
          value: "/ussss"
